import { SurfSpot } from "./types";

export const surfSpots: SurfSpot[] = [
  {
    id: "peniche",
    name: "Peniche",
    country: "Portugal",
    city: "Peniche",
    region: "Central Portugal",
    image:
      "https://images.winalist.com/blog/wp-content/uploads/2025/04/12095324/adobestock-692602795-1500x999.jpeg",
    description:
      "Peniche is a world-renowned surf destination and home to the famous Supertubos beach, hosting international competitions. This historic fishing town offers consistent waves year-round with various breaks suitable for different skill levels.",
    level: "All Levels",
    bestSeason: "September to May",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1-3m (up to 6m at Supertubos)",
    crowd: "Can be crowded at main spots",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Board rentals",
      "Parking",
      "Restaurants",
      "Surf shops",
    ],
    affiliateStays: [
      { name: "Peniche Surf Lodge", url: "https://booking.com" },
      { name: "Casa do Castelo Guesthouse", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Baleal Surf Camp", url: "https://example.com" },
      { name: "Peniche Boat Tours", url: "https://example.com" },
    ],
  },
  {
    id: "ericeira",
    name: "Ericeira",
    country: "Portugal",
    city: "Ericeira",
    region: "Lisbon Area",
    image:
      "https://www.portugal.net/en/wp-content/uploads/sites/107/ericeira.jpg",
    description:
      "Europe's first World Surfing Reserve, Ericeira is a charming fishing village with pristine beaches and world-class waves. The area features multiple reef breaks and is famous for powerful right-handers like Coxos and Ribeira d'Ilhas.",
    level: "Intermediate to Advanced",
    bestSeason: "October to April",
    waveType: "Reef break, point break",
    averageWaveHeight: "1.5-3m",
    crowd: "Moderate to crowded",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Surf camps",
      "Equipment rental",
      "Restaurants",
      "Nightlife",
    ],
    affiliateStays: [
      { name: "Ericeira Surf House", url: "https://booking.com" },
      { name: "Hotel Vila Galé Ericeira", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Coxos Surf School", url: "https://example.com" },
      { name: "Coastal Hike to Ribeira d'Ilhas", url: "https://example.com" },
    ],
  },
  {
    id: "nazare",
    name: "Nazaré",
    country: "Portugal",
    city: "Nazaré",
    region: "Central Portugal",
    image:
      "https://ichef.bbci.co.uk/ace/standard/1024/cpsprodpb/3A83/production/_129097941_nazare_getty.jpg",
    description:
      "Famous for the biggest waves in the world, Nazaré became legendary when surfers like Garrett McNamara rode 100-foot waves. While the massive Praia do Norte is for elite big wave surfers only, the main beach offers gentler waves perfect for learning.",
    level: "All Levels",
    bestSeason: "October to March (big waves)",
    waveType: "Beach break, big wave",
    averageWaveHeight: "1-2m (main beach), 15-30m (Praia do Norte)",
    crowd: "Touristy but spacious",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Rentals",
      "Parking",
      "Restaurants",
      "Viewpoints",
    ],
    affiliateStays: [
      { name: "Magic Wave Hostel", url: "https://booking.com" },
      { name: "Hotel Praia", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Nazaré Surf Experience", url: "https://example.com" },
      { name: "Fort of São Miguel Tour", url: "https://example.com" },
    ],
  },
  {
    id: "sagres",
    name: "Sagres",
    country: "Portugal",
    city: "Sagres",
    region: "Algarve",
    image:
      "https://thealgarvefamily.com/wp-content/uploads/2022/12/Mareta-beach-things-to-do-in-sagres.jpg",
    description:
      "Located at the southwestern tip of Europe, Sagres offers dramatic cliffs, pristine beaches, and consistent surf. The area provides protection from various wind directions and features beautiful scenery with a laid-back atmosphere perfect for surf trips.",
    level: "Intermediate",
    bestSeason: "September to May",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1-2.5m",
    crowd: "Less crowded",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Equipment rental",
      "Camping",
      "Restaurants",
      "Natural beauty",
    ],
    affiliateStays: [
      { name: "Sagres Natura Surf Camp", url: "https://booking.com" },
      { name: "Memmo Baleeira Hotel", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Sagres Surf School", url: "https://example.com" },
      { name: "Cape St. Vincent Sunset Tour", url: "https://example.com" },
    ],
  },
  {
    id: "carcavelos",
    name: "Carcavelos",
    country: "Portugal",
    city: "Cascais",
    region: "Lisbon Coast",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/9a/60/c4/praia-de-carcavelos.jpg?w=900&h=500&s=1",
    description:
      "Just 20 minutes from Lisbon, Carcavelos is the most accessible surf spot near the capital. This long sandy beach offers consistent waves and is popular among locals and surf schools, making it ideal for beginners and improving intermediates.",
    level: "Beginner to Intermediate",
    bestSeason: "September to May",
    waveType: "Beach break",
    averageWaveHeight: "0.5-2m",
    crowd: "Very crowded",
    costOfLiving: "High",
    facilities: [
      "Multiple surf schools",
      "Board rentals",
      "Beach bars",
      "Showers",
      "Easy access",
    ],
    affiliateStays: [
      { name: "Lisbon Surf Camp Carcavelos", url: "https://booking.com" },
      { name: "Oitavos Hotel", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Moana Surf School", url: "https://example.com" },
      { name: "Cascais Historical Walking Tour", url: "https://example.com" },
    ],
  },
  {
    id: "arrifana",
    name: "Arrifana",
    country: "Portugal",
    city: "Aljezur",
    region: "Southwest Alentejo",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2z7Kr8G7MJim8hsFDPDSmSjXxLYmdES6-Pw&s",
    description:
      "Hidden gem in the Costa Vicentina Natural Park, Arrifana features a stunning horseshoe bay surrounded by dramatic cliffs. The beach offers both left and right breaks with powerful, hollow waves that attract experienced surfers seeking uncrowded perfection.",
    level: "Intermediate to Advanced",
    bestSeason: "September to May",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1.5-3m",
    crowd: "Moderate",
    costOfLiving: "Low",
    facilities: [
      "Surf school",
      "Restaurant",
      "Limited parking",
      "Natural park",
    ],
    affiliateStays: [
      { name: "Monte Velho Nature Resort", url: "https://booking.com" },
      { name: "Arrifana Surf Lodge", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Arrifana Surf Academy", url: "https://example.com" },
      { name: "Rota Vicentina Hiking", url: "https://example.com" },
    ],
  },
  {
    id: "san-sebastian",
    name: "San Sebastián",
    country: "Spain",
    city: "San Sebastián",
    region: "Basque Country",
    image:
      "https://www.sansebastian.travel/en/wp-content/uploads/sites/2/2013/04/Zurriola-beach.jpg",
    description:
      "La Zurriola beach in San Sebastián is the heart of Basque surf culture. This urban beach offers consistent waves in a stunning city setting with world-class gastronomy and vibrant nightlife just steps from the shore.",
    level: "Beginner to Intermediate",
    bestSeason: "September to May",
    waveType: "Beach break",
    averageWaveHeight: "0.5-2m",
    crowd: "Crowded",
    costOfLiving: "High",
    facilities: [
      "Multiple surf schools",
      "Equipment rental",
      "Showers",
      "Beach clubs",
      "Restaurants",
    ],
    affiliateStays: [
      { name: "Surfer's Paradise Hotel", url: "https://booking.com" },
      { name: "San Sebastián Surf House", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Pukas Surf School", url: "https://example.com" },
      { name: "Pintxos Food Tour", url: "https://example.com" },
    ],
  },
  {
    id: "mundaka",
    name: "Mundaka",
    country: "Spain",
    city: "Mundaka",
    region: "Basque Country",
    image:
      "https://d14fqx6aetz9ka.cloudfront.net/wp-content/uploads/2017/08/28163127/esp_northeastspain_mundaka.jpg",
    description:
      "Home to one of Europe's most famous left-hand waves, Mundaka is a bucket-list destination for advanced surfers. The river mouth creates a perfect barrel that can hold up to 12 feet, drawing top surfers from around the world.",
    level: "Advanced to Professional",
    bestSeason: "September to March",
    waveType: "Point break, river mouth",
    averageWaveHeight: "2-4m (up to 12ft)",
    crowd: "Very crowded when working",
    costOfLiving: "Medium",
    facilities: [
      "Limited facilities",
      "Local surf shops",
      "Restaurants",
      "Parking",
    ],
    affiliateStays: [
      { name: "Mundaka Surf Lodge", url: "https://booking.com" },
      { name: "Urdaibai Hotel", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Mundaka Surf Tours", url: "https://example.com" },
      { name: "Urdaibai Biosphere Reserve Tour", url: "https://example.com" },
    ],
  },
  {
    id: "hossegor",
    name: "Hossegor",
    country: "France",
    city: "Hossegor",
    region: "Les Landes",
    image:
      "https://cdn.sanity.io/images/we0tdimr/production/79b5bdad9b00f17f5d23f50d48bc2723061d3210-3840x2560.jpg?rect=0,200,3840,2160&w=1920&h=1080&q=70&auto=format",
    description:
      "Known as the European surf capital, Hossegor features powerful beach breaks and hosts the world's best in professional competitions. La Gravière offers some of the heaviest beach break barrels in the world.",
    level: "Intermediate to Advanced",
    bestSeason: "September to November",
    waveType: "Beach break, heavy barrels",
    averageWaveHeight: "1.5-3m (up to 6m)",
    crowd: "Very crowded",
    costOfLiving: "High",
    facilities: [
      "Numerous surf schools",
      "Surf shops",
      "Beach clubs",
      "Restaurants",
      "Nightlife",
    ],
    affiliateStays: [
      { name: "Hossegor Surf Camp", url: "https://booking.com" },
      { name: "Hôtel de la Plage", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Quiksilver Pro France Experience", url: "https://example.com" },
      { name: "Les Landes Pine Forest Cycling", url: "https://example.com" },
    ],
  },
  {
    id: "biarritz",
    name: "Biarritz",
    country: "France",
    city: "Biarritz",
    region: "French Basque Coast",
    image:
      "https://images.ctfassets.net/zmjc9gr9hbbf/5RKEfQjzISDIgHbKti8TWq/b5c527763a814ebb1786085e0ab3a0a5/St_Biarritz_2700px_AQU36797.jpg?w=1980",
    description:
      "The birthplace of European surfing, Biarritz combines elegant Belle Époque architecture with excellent surf. Grande Plage and Côte des Basques offer waves for all levels in this sophisticated seaside resort.",
    level: "All Levels",
    bestSeason: "September to May",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1-2.5m",
    crowd: "Moderate to crowded",
    costOfLiving: "High",
    facilities: [
      "Multiple surf schools",
      "Historic surf clubs",
      "Luxury amenities",
      "Fine dining",
      "Museums",
    ],
    affiliateStays: [
      { name: "Hôtel du Palais", url: "https://booking.com" },
      { name: "Biarritz Surf Residence", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Jo Moraiz Surf School", url: "https://example.com" },
      { name: "Biarritz Lighthouse & Museum", url: "https://example.com" },
    ],
  },
  {
    id: "newquay",
    name: "Newquay",
    country: "United Kingdom",
    city: "Newquay",
    region: "Cornwall",
    image:
      "https://lovenqy.co.uk/wp-content/uploads/2023/10/Explore-landing-size-3.png",
    description:
      "Britain's surf capital, Newquay offers consistent Atlantic swells hitting dramatic Cornish cliffs. Fistral Beach is the crown jewel, hosting major competitions and offering world-class waves with a uniquely British surf culture.",
    level: "All Levels",
    bestSeason: "September to March",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1-2.5m (up to 4m)",
    crowd: "Moderate to crowded",
    costOfLiving: "Medium",
    facilities: [
      "Many surf schools",
      "Surf shops",
      "Beach cafes",
      "Hostels",
      "Surf museums",
    ],
    affiliateStays: [
      { name: "Fistral Beach Hotel", url: "https://booking.com" },
      { name: "Newquay Surf Lodge", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "British Surfing Museum", url: "https://example.com" },
      { name: "Cornwall Coastal Path Hiking", url: "https://example.com" },
    ],
  },
  {
    id: "bundoran",
    name: "Bundoran",
    country: "Ireland",
    city: "Bundoran",
    region: "County Donegal",
    image:
      "https://thesurfatlas.com/wp-content/uploads/2024/04/Bundoran-surf.jpg",
    description:
      "Known as Ireland's surf capital, Bundoran features powerful Atlantic swells and dramatic scenery. The Peak offers world-class reef breaks while the main beach is perfect for beginners. Embrace the cold water and friendly Irish surf community.",
    level: "All Levels",
    bestSeason: "September to April",
    waveType: "Beach break, reef break",
    averageWaveHeight: "1-3m (up to 6m)",
    crowd: "Moderate",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Wetsuit rentals",
      "Surf shops",
      "Pubs",
      "Accommodation",
    ],
    affiliateStays: [
      { name: "Bundoran Surf Co Lodge", url: "https://booking.com" },
      { name: "Great Northern Hotel", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Bundoran Surf School", url: "https://example.com" },
      { name: "Wild Atlantic Way Tour", url: "https://example.com" },
    ],
  },
  {
    id: "lahinch",
    name: "Lahinch",
    country: "Ireland",
    city: "Lahinch",
    region: "County Clare",
    image: "https://visitclare.ie/wp-content/uploads/2023/01/Lahinch.png",
    description:
      "A picturesque Irish surf village with a stunning crescent bay, Lahinch offers consistent waves and breathtaking Cliffs of Moher nearby. The friendly local surf community and traditional Irish pubs create an authentic surf experience.",
    level: "Beginner to Intermediate",
    bestSeason: "September to May",
    waveType: "Beach break",
    averageWaveHeight: "1-2.5m",
    crowd: "Moderate",
    costOfLiving: "Medium",
    facilities: [
      "Surf schools",
      "Equipment rental",
      "Beach facilities",
      "Restaurants",
      "Irish pubs",
    ],
    affiliateStays: [
      { name: "Lahinch Surf House", url: "https://booking.com" },
      { name: "Atlantic Hotel", url: "https://booking.com" },
    ],
    affiliateActivities: [
      { name: "Lahinch Surf School", url: "https://example.com" },
      { name: "Cliffs of Moher Tour", url: "https://example.com" },
    ],
  },
];
